// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Create a new user
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Delete a user by ID
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	// Get a user by ID
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	// List all users
	ListUsers(ctx context.Context) ([]User, error)
	// Update a user by ID
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
