// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type UserRole string

const (
	UserRoleMaster   UserRole = "master"
	UserRoleVendor   UserRole = "vendor"
	UserRoleCustomer UserRole = "customer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"userRole"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Commission struct {
	ID               uuid.UUID `json:"id"`
	OrderID          uuid.UUID `json:"orderId"`
	UserID           uuid.UUID `json:"userId"`
	CommissionAmount string    `json:"commissionAmount"`
	PaidStatus       string    `json:"paidStatus"`
}

type Customer struct {
	ID        uuid.UUID `json:"id"`
	StoreID   uuid.UUID `json:"storeId"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
	Address   string    `json:"address"`
}

type Link struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"userId"`
	UniqueLink string    `json:"uniqueLink"`
	LinkType   string    `json:"linkType"`
}

type Order struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"userId"`
	OrderDate       time.Time `json:"orderDate"`
	TotalAmount     string    `json:"totalAmount"`
	Status          string    `json:"status"`
	PaymentStatus   string    `json:"paymentStatus"`
	ShippingAddress string    `json:"shippingAddress"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type OrderItem struct {
	ID        uuid.UUID `json:"id"`
	OrderID   uuid.UUID `json:"orderId"`
	ProductID uuid.UUID `json:"productId"`
	Quantity  int32     `json:"quantity"`
	UnitPrice string    `json:"unitPrice"`
	Subtotal  string    `json:"subtotal"`
}

type Product struct {
	ID            uuid.UUID `json:"id"`
	StoreID       uuid.UUID `json:"storeId"`
	Sku           string    `json:"sku"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	Price         string    `json:"price"`
	StockQuantity int32     `json:"stockQuantity"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type Store struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"userId"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
	Image     string    `json:"image"`
	GoogleID  string    `json:"googleId"`
	Role      UserRole  `json:"role"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
