// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: order.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  user_id, order_date, total_amount, status, payment_status, shipping_address, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, order_date, total_amount, status, payment_status, shipping_address, created_at, updated_at
`

type CreateOrderParams struct {
	UserID          uuid.UUID `json:"userId"`
	OrderDate       time.Time `json:"orderDate"`
	TotalAmount     string    `json:"totalAmount"`
	Status          string    `json:"status"`
	PaymentStatus   string    `json:"paymentStatus"`
	ShippingAddress string    `json:"shippingAddress"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

// Create a new order
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.OrderDate,
		arg.TotalAmount,
		arg.Status,
		arg.PaymentStatus,
		arg.ShippingAddress,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderDate,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentStatus,
		&i.ShippingAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

// Delete an order by ID
func (q *Queries) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrder, id)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, order_date, total_amount, status, payment_status, shipping_address, created_at, updated_at FROM orders
WHERE id = $1 LIMIT 1
`

// Get an order by ID
func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderDate,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentStatus,
		&i.ShippingAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, user_id, order_date, total_amount, status, payment_status, shipping_address, created_at, updated_at FROM orders
ORDER BY order_date
`

// List all orders
func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderDate,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentStatus,
			&i.ShippingAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :exec
UPDATE orders
SET
  user_id = $2,
  order_date = $3,
  total_amount = $4,
  status = $5,
  payment_status = $6,
  shipping_address = $7,
  created_at = $8,
  updated_at = $9
WHERE id = $1
`

type UpdateOrderParams struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"userId"`
	OrderDate       time.Time `json:"orderDate"`
	TotalAmount     string    `json:"totalAmount"`
	Status          string    `json:"status"`
	PaymentStatus   string    `json:"paymentStatus"`
	ShippingAddress string    `json:"shippingAddress"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

// Update an order by ID
func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateOrder,
		arg.ID,
		arg.UserID,
		arg.OrderDate,
		arg.TotalAmount,
		arg.Status,
		arg.PaymentStatus,
		arg.ShippingAddress,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
