// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: product_images.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (product_id, url)
VALUES ($1, $2)
RETURNING id, product_id, url
`

type CreateProductImageParams struct {
	ProductID uuid.UUID `json:"productId"`
	Url       string    `json:"url"`
}

// Create a product image for a product:
func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, createProductImage, arg.ProductID, arg.Url)
	var i ProductImage
	err := row.Scan(&i.ID, &i.ProductID, &i.Url)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_images
WHERE id = $1
RETURNING id, product_id, url
`

// Delete a product image by ID:
func (q *Queries) DeleteProductImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductImage, id)
	return err
}

const getProductImage = `-- name: GetProductImage :one
SELECT id, product_id, url FROM product_images
WHERE id = $1 LIMIT 1
`

// Get a product image by ID:
func (q *Queries) GetProductImage(ctx context.Context, id uuid.UUID) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, getProductImage, id)
	var i ProductImage
	err := row.Scan(&i.ID, &i.ProductID, &i.Url)
	return i, err
}

const listProductImagesForProduct = `-- name: ListProductImagesForProduct :many
SELECT id, product_id, url FROM product_images
WHERE product_id = $1
`

// List all product images for a product:
func (q *Queries) ListProductImagesForProduct(ctx context.Context, productID uuid.UUID) ([]ProductImage, error) {
	rows, err := q.db.QueryContext(ctx, listProductImagesForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(&i.ID, &i.ProductID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductImage = `-- name: UpdateProductImage :exec
UPDATE product_images
SET
  url = $2
WHERE id = $1
RETURNING id, product_id, url
`

type UpdateProductImageParams struct {
	ID  uuid.UUID `json:"id"`
	Url string    `json:"url"`
}

// Update a product image by ID:
func (q *Queries) UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) error {
	_, err := q.db.ExecContext(ctx, updateProductImage, arg.ID, arg.Url)
	return err
}
